
stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    - notebooks/emotions/training.csv
    - notebooks/emotions/test.csv
    - notebooks/emotions/validation.csv
    outs:
    - data/raw/train.csv
    - data/raw/test.csv
    - data/raw/valid.csv

  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
    - data/raw/train.csv
    - data/raw/test.csv
    - data/raw/valid.csv
    - src/data/data_preprocessing.py
    outs:
    - data/interim/train_processed.csv
    - data/interim/test_processed.csv
    - data/interim/validation_processed.csv

  feature_engineering:
    cmd: python src/features/feature_engineering.py
    deps:
    - data/interim/train_processed.csv
    - data/interim/test_processed.csv
    - data/interim/validation_processed.csv
    - src/features/feature_engineering.py
    params:
    - feature_engineering.batch_size
    - feature_engineering.max_len
    - feature_engineering.embedding_dim
    - feature_engineering.num_words
    outs:
    - data/interim/train_bpe.csv
    - data/interim/test_bpe.csv
    - data/interim/validation_bpe.csv
    - data/interim/train_bpe.npy
    - data/interim/test_bpe.npy
    - data/interim/validation_bpe.npy

  train_model:
    cmd: python src/model/train_model.py
    deps:
    - data/interim/train_bpe.npy
    - data/interim/validation_bpe.npy
    - data/interim/train_bpe.csv
    - data/interim/validation_bpe.csv
    - src/model/train_model.py
    params:
    - train_model.batch_size
    - train_model.max_len
    - train_model.embedding_dim
    - train_model.epochs
    outs:
    - models/model.h5

  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
    - models/model.h5
    - src/model/model_evaluation.py
    metrics:
    - reports/metrics.json
    outs:
    - reports/experiment_info.json  

  model_registration:
    cmd: python src/model/register_model.py
    deps:
    - reports/experiment_info.json
    - src/model/register_model.py

